### ISSUE TITLE
some colorful slimes

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Mod-OptiFine-McPatcher#1]
![slime12](https://cloud.githubusercontent.com/assets/16853304/15942419/9319cfac-2e84-11e6-9618-05c5949e946c.png)
![slime13](https://cloud.githubusercontent.com/assets/16853304/15942421/94995488-2e84-11e6-935c-4beee8408e03.png)
![slime14](https://cloud.githubusercontent.com/assets/16853304/15942425/95d47aa8-2e84-11e6-8b2b-4ccbd72d3499.png)
![slime15](https://cloud.githubusercontent.com/assets/16853304/15942428/971d91b0-2e84-11e6-907a-b935a828b90c.png)

**Comment by tobyplowy** [comment]
They look like candy :D

**Comment by lipki** [comment]
There are already a lot of different slime, put ok it's more.

**Comment by lipki** [comment]
Added
