### ISSUE TITLE
new squid texture

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Mod-OptiFine-McPatcher#2]
![squid7](https://cloud.githubusercontent.com/assets/16853304/15942549/23478e16-2e85-11e6-830e-17fece1fb946.png)

**Comment by FlorianDoyen95** [comment]
I create new texture for squid, what do you think about ? :D

![squid6](https://user-images.githubusercontent.com/23485756/28491526-ba7939b0-6ef3-11e7-81ab-96e9392f2b69.png)![squid7](https://user-images.githubusercontent.com/23485756/28491527-ba794284-6ef3-11e7-80d5-d5e4484a07db.png)![squid8](https://user-images.githubusercontent.com/23485756/28491525-ba7776a2-6ef3-11e7-814c-4c4c3ab68477.png)![squid9](https://user-images.githubusercontent.com/23485756/28491528-ba7ae274-6ef3-11e7-8b2e-3be4a2a5c03d.png)![squid10](https://user-images.githubusercontent.com/23485756/28491524-ba74dcbc-6ef3-11e7-8f59-64822acd6761.png)![squid11](https://user-images.githubusercontent.com/23485756/28491529-ba7c35ac-6ef3-11e7-9ed3-6299ae14751d.png)![squid12](https://user-images.githubusercontent.com/23485756/28491530-ba8ef2aa-6ef3-11e7-9766-6a186c31482f.png)![squid13](https://user-images.githubusercontent.com/23485756/28491531-baa3ca04-6ef3-11e7-93fd-476eb127bd46.png)![squid14](https://user-images.githubusercontent.com/23485756/28491532-baa64018-6ef3-11e7-8232-a18953076c89.png)![squid15](https://user-images.githubusercontent.com/23485756/28491533-baa6952c-6ef3-11e7-91e8-acc424c3c55f.png)![squid16](https://user-images.githubusercontent.com/23485756/28491534-baa6d456-6ef3-11e7-870f-ccd3674c4ee5.png)

**Comment by lipki** [comment]
For info, there are already these.

![squid](https://user-images.githubusercontent.com/401965/28493958-fba7bf10-6f20-11e7-9579-eaaf24dc14c2.png)

![squid2](https://user-images.githubusercontent.com/401965/28493953-dd66ace6-6f20-11e7-96c0-4047be1a0283.png)![squid3](https://user-images.githubusercontent.com/401965/28493954-dd66d7b6-6f20-11e7-8b6d-4c28bae1ec06.png)![squid4](https://user-images.githubusercontent.com/401965/28493955-dd66f9d0-6f20-11e7-9483-170ab3ab9d10.png)![squid5](https://user-images.githubusercontent.com/401965/28493956-dd68b77a-6f20-11e7-8ae2-ff0dd46aa643.png)![squid6](https://user-images.githubusercontent.com/401965/28493957-dd6c44e4-6f20-11e7-83a0-34af54eb7298.png)

**Comment by lipki** [comment]
Added
![Capture d’écran du 2020-10-26 12-36-24](https://user-images.githubusercontent.com/401965/97167951-f7c77580-1787-11eb-9a79-66f0a62637e9.png)
